# Generated by Django 4.2.16 on 2025-01-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanquetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='hall_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('cnic_number', models.CharField(max_length=15, unique=True)),
                ('cnic_pictures', models.ImageField(blank=True, null=True, upload_to='cnic_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Booking.banquetdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Booking.userdetail')),
            ],
            options={
                'unique_together': {('banquet', 'event_date', 'start_time', 'end_time')},
            },
        ),
    ]
