# Generated by Django 4.2.16 on 2025-01-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingdetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='bookingdetail',
            unique_together={('banquet', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='bookingdetail',
            name='event_date',
        ),
    ]
