# Generated by Django 4.2.16 on 2025-01-07 12:37

import Booking.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_bookingdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='cnic_number',
            field=models.CharField(max_length=15, unique=True, validators=[Booking.validator.validate_cnic]),
        ),
    ]
